language: php

php:
#  - 5.2
  - 5.3
#  - 5.4
#  - 5.5

before_script:
  - composer install
  - wget http://codeception.com/codecept.phar
  - sudo apt-get install -y apache2 php5
  - sudo a2enmod rewrite
  - echo "export PUBLIC_PATH=`pwd`/tests/_public/" | sudo tee -a /etc/apache2/envvars > /dev/null
  - sudo cp tests/_apache/sites-available/default /etc/apache2/sites-available/default
  - sudo service apache2 restart

script: php codecept.phar run