language: php

php:
#  - 5.2
  - 5.3
#  - 5.4
#  - 5.5

services:
#  - redis-server
#  - memcached

before_script:
  - composer install
  - wget http://codeception.com/codecept.phar

script: php codecept.phar run